repos:
  # ==================== Black ====================
  - repo: https://github.com/psf/black
    rev: 25.12.0
    hooks:
      - id: black
        name: formatting Python code (Black)
        language_version: python3.11
        files: ^backend/.*\.py$
        exclude: ^backend/.*/migrations/.*\.py$

  # ==================== isort  ====================
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        name: Sorting import statement (isort)
        args: ["--profile", "black"]
        files: ^backend/.*\.py$
        exclude: ^backend/.*/migrations/.*\.py$

  # ==================== Flake8====================
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        name: Check for code errors (Flake8)
        args:
          - --max-line-length=127
          - --ignore=E501,W503,E203,C901,F841,E402
          - --exclude=*/migrations/*,venv,env,__pycache__,*.pyc,settings.py
          - --max-complexity=20
        files: ^backend/.*\.py$

  # ====================other ====================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        files: ^backend/.*\.py$

      - id: trailing-whitespace
        files: ^backend/.*\.py$

      - id: check-merge-conflict

      - id: check-yaml
        files: \.(yaml|yml)$

      - id: check-added-large-files
        args: ['--maxkb=10240']
